// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Skeinkeeper Contributors

import type { TTSProvider } from "../interfaces/voice.js";
import type { LLMProvider } from "../interfaces/llm.js";
import type { SessionConfig } from "../session.js";
import { extractFirstJsonObject } from "../util/extract_json.js";

/**
 * Cached pause/resume TTS announcements (design doc 0039 §3 step 3 / §4
 * step 3). Generated by the LLM once at session-setup time so NO LLM call is
 * needed at pause-time — the cached string is the only thing TTS'd. The audio
 * is also pre-rendered defensively; the text remains the fallback.
 */

export interface CachedAnnouncement {
  /** Pre-rendered TTS. Empty when the pre-render failed (text still usable). */
  audio: Buffer;
  /** For fallback if voice is down too (impossible per current scope but defensive). */
  text: string;
}

export interface LifecycleAnnouncements {
  pauseFoundryDown: CachedAnnouncement;
  resumeOk: CachedAnnouncement;
}

/** Fallbacks when the one-shot generation fails — session start must not block
 *  on announcement generation. Phrasing guidance lives in behavior/default.md. */
export const DEFAULT_PAUSE_ANNOUNCEMENT =
  "I'm pausing the session — looks like Foundry's lost contact. " +
  "We'll resume when the operator's restored it.";
export const DEFAULT_RESUME_ANNOUNCEMENT = "We're back. Picking up where we left off.";

const GENERATION_INSTRUCTION =
  "Out of character: generate the two short spoken announcements you will use if the " +
  "Foundry table connection drops mid-session. Requirements: generic (no campaign or " +
  "scene specifics, no spoilers), calm, one or two sentences each. The pause line tells " +
  "the table you're pausing because Foundry lost contact and the operator will restore " +
  "it; the resume line acknowledges the gap and picks the session back up. Reply with " +
  'ONLY a JSON object: {"pause": "...", "resume": "..."}';

export async function prepareLifecycleAnnouncements(args: {
  llm: LLMProvider;
  tts: TTSProvider;
  config: SessionConfig;
  /** TTS voice for the pre-render (the DM voice). Provider default if absent. */
  voiceId?: string;
}): Promise<LifecycleAnnouncements> {
  const { pause, resume } = await generateTexts(args.llm, args.config);
  const [pauseAudio, resumeAudio] = await Promise.all([
    render(args.tts, pause, args.voiceId),
    render(args.tts, resume, args.voiceId),
  ]);
  return {
    pauseFoundryDown: { audio: pauseAudio, text: pause },
    resumeOk: { audio: resumeAudio, text: resume },
  };
}

async function generateTexts(
  llm: LLMProvider,
  config: SessionConfig,
): Promise<{ pause: string; resume: string }> {
  const fallback = { pause: DEFAULT_PAUSE_ANNOUNCEMENT, resume: DEFAULT_RESUME_ANNOUNCEMENT };
  try {
    let text = "";
    const stream = llm.complete({
      systemPrompt: config.behaviorSpec.content,
      messages: [{ role: "user", content: [{ type: "text", text: GENERATION_INSTRUCTION }] }],
      tools: [],
      modelTier: "orchestration",
    });
    for await (const ev of stream) {
      if (ev.kind === "text_delta") text += ev.text;
      else if (ev.kind === "error") return fallback;
    }
    const parsed = extractFirstJsonObject(text);
    const pause = parsed?.["pause"];
    const resume = parsed?.["resume"];
    if (typeof pause !== "string" || pause.length === 0) return fallback;
    if (typeof resume !== "string" || resume.length === 0) return fallback;
    return { pause, resume };
  } catch {
    return fallback;
  }
}

async function render(tts: TTSProvider, text: string, voiceId?: string): Promise<Buffer> {
  try {
    const bytes = await tts.synthesize(text, voiceId !== undefined ? { voiceId } : undefined);
    return Buffer.from(bytes);
  } catch {
    // Pre-render is best-effort; pause-time falls back to TTS'ing the text.
    return Buffer.alloc(0);
  }
}
